### ISSUE TITLE
When training the segmentation the code seems stuck

### ISSUE THREAD

**Issue by xingy038** [Kunhao-Liu/3D-OVS#3]
<img width="884" alt="image" src="https://github.com/Kunhao-Liu/3D-OVS/assets/105112213/c6962452-7590-468e-8aba-1d70b94c8c18">

**Comment by ljnsysu** [comment]
I'm also stuck here, have u fixed this? thx!!!

**Comment by xingy038** [comment]
Change the work_number. The original code is setting 8.

At 2024-03-28 14:59:13, "dimi_37" ***@***.***> wrote:

I'm also stuck here, have u fixed this? thx!!!

**Comment by ljnsysu** [comment]
> Change the work_number. The original code is setting 8. At 2024-03-28 14:59:13, "dimi_37" ***@***.***> wrote: I'm also stuck here, have u fixed this? thx!!! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

fixed! Thank you!!!
